version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: gestao-vendas_app:latest
    container_name: gestao_vendas_app
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - jaeger
      - prometheus
      - grafana
    command: ["-c", "/app/wait-for-mysql.sh mysql:3306 && java -jar /app/gestao_vendas.jar"]
    entrypoint: ["/bin/sh"]

  mysql:
    image: mysql:8.0.30
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: gvendas
      MYSQL_PASSWORD: gvendas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gvendas_db

  jaeger:
    image: jaegertracing/all-in-one:1.37
    container_name: jaeger
    ports:
        - 6831:6831/udp
        - 6832:6832/udp
        - 5778:5778
        - 16686:16686
        - 4317:4317
        - 4318:4318
        - 14250:14250
        - 14268:14268
        - 14269:14269
        - 9411:9411
    
  prometheus:
    image: prom/prometheus:v2.38.0
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:9.1.2
    container_name: grafana
    ports:
      - 3000:3000