{
 "title": "Gestao Vendas",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Produto COUNT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/produto\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/produto/{codigo}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/produto/{codigo}/categoria/{codigoCategoria}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/produto/categoria/{codigoCategoria}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Categoria COUNT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/categoria/{codigo}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/categoria\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Produto SUM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{job=\"gestao-vendas\", uri=\"/produto\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{job=\"gestao-vendas\", uri=\"/produto/{codigo}/categoria/{codigoCategoria}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{job=\"gestao-vendas\", uri=\"/produto/categoria/{codigoCategoria}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{job=\"gestao-vendas\", uri=\"/produto/{codigo}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Categoria SUM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{job=\"gestao-vendas\", uri=\"/categoria\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{job=\"gestao-vendas\", uri=\"/categoria/{codigo}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Produto MAX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"gestao-vendas\", uri=\"/produto/{codigo}/categoria/{codigoCategoria}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{job=\"gestao-vendas\", uri=\"/produto/{codigo}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{job=\"gestao-vendas\", uri=\"/produto/categoria/{codigoCategoria}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{job=\"gestao-vendas\", uri=\"/produto\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Categoria MAX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"gestao-vendas\", uri=\"/categoria\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{job=\"gestao-vendas\", uri=\"/categoria/{codigo}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Cliente COUNT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/cliente\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/cliente/{codigo}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Venda COUNT",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/venda/{codigoVenda}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/venda/cliente/{codigoCliente}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/venda/{codigoVenda}/cliente/{codigoCliente}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Cliente SUM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{job=\"gestao-vendas\", uri=\"/cliente\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_sum{job=\"gestao-vendas\", uri=\"/cliente/{codigo}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Venda SUM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{job=\"gestao-vendas\", uri=\"/venda/{codigoVenda}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/venda/cliente/{codigoCliente}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/venda/{codigoVenda}/cliente/{codigoCliente}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Cliente MAX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"gestao-vendas\", uri=\"/cliente\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_max{job=\"gestao-vendas\", uri=\"/cliente/{codigo}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  },
  {
   "title": "Venda MAX",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_max{job=\"gestao-vendas\", uri=\"/venda/{codigoVenda}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/venda/cliente/{codigoCliente}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    },
    {
     "expr": "http_server_requests_seconds_count{job=\"gestao-vendas\", uri=\"/venda/{codigoVenda}/cliente/{codigoCliente}\"}",
     "legendFormat": "{{method}}/{{outcome}}/{{status}}"
    }
   ]
  }
 ]
}